{% set name = "napari-geojson" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d376f4a658573d32ab99410411184c61db3d14869eede7648a3bc92958912d71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - geojson
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_geojson
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tdmorello/napari-geojson
  summary: Read and write geojson files in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tdmorello
